### ISSUE TITLE
Service install error

### ISSUE THREAD

**Issue by Seanc24** [iso8859/FileNotify2#1]
Under windows 10 (1809) the service can not be installed, resulting the following entry in the log file:
Installation de l'assembly 'C:\FileNotify2\fnService.exe'.
Les paramètres affectés sont :
   logtoconsole = 
   assemblypath = C:\FileNotify2\fnService.exe
   logfile = C:\FileNotify2\fnService.InstallLog
Installation du service FileNotify2 en cours...
Création d'une source EventLog FileNotify2 dans le journal Application...
Restauration de l'assembly 'C:\FileNotify2\fnService.exe'.
Les paramètres affectés sont :
   logtoconsole = 
   assemblypath = C:\FileNotify2\fnService.exe
   logfile = C:\FileNotify2\fnService.InstallLog
Restauration de l'état précédent du journal des événements pour la source FileNotify2.

**Comment by iso8859** [comment]
Hi,
Just update the project and created fnService2 project that uses Topshelf https://github.com/Topshelf/Topshelf library as service manager.

**Comment by Seanc24** [comment]
Hi,

 

Thank you for your quick action in fixing the problem. You didn’t compile the prog with the update so I cannot get new files. How can I compile with the source files on my PC? (Sorry I’m not a developer ☹

 

Regards

 

 

De : Rémi THOMAS <notifications@github.com> 
Envoyé : mardi 11 juin 2019 16:29
À : iso8859/FileNotify2 <FileNotify2@noreply.github.com>
Cc : Seanc24 <sean.coulon@orange.fr>; Author <author@noreply.github.com>
Objet : Re: [iso8859/FileNotify2] Service install error (#1)

 

Hi,
Just update the project and created fnService2 project that uses Topshelf https://github.com/Topshelf/Topshelf library as service manager.

**Comment by iso8859** [comment]
Hi,
Just compile it for you.
https://github.com/iso8859/FileNotify2/blob/master/setup/bin.zip

**Comment by Seanc24** [comment]
Thank you !

 

De : Rémi THOMAS <notifications@github.com> 
Envoyé : mercredi 12 juin 2019 10:19
À : iso8859/FileNotify2 <FileNotify2@noreply.github.com>
Cc : Seanc24 <sean.coulon@orange.fr>; Author <author@noreply.github.com>
Objet : Re: [iso8859/FileNotify2] Service install error (#1)

 

Hi,
Just compile it for you.
https://github.com/iso8859/FileNotify2/blob/master/setup/bin.zip
